export type FeatureStatus = 'implemented' | 'excluded' | 'replaced'

export interface FeatureDefinition {
  id: string
  name: string
  category: string
  purpose: string
  location: string
  activation: string
  shortcut?: string
  defaultState: string
  dependencies: string
  privacy: string
  processedData: string
  disable: string
  status: FeatureStatus
}

type FeatureInput = Omit<FeatureDefinition, 'status'> & { status?: FeatureStatus }

function feature(input: FeatureInput): FeatureDefinition {
  return { status: 'implemented', ...input }
}

const local = 'Runs locally in this browser.'
const settings = 'Reader settings'

export const featureRegistry: FeatureDefinition[] = [
  feature({ id: 'document-import', name: 'Document import', category: 'Documents', purpose: 'Open PDF, EPUB, DOC, DOCX, TXT, and HTML files with source mapping.', location: 'Reader upload', activation: 'Choose Upload.', defaultState: 'Available', dependencies: 'Local Celere parser server', privacy: 'Files are parsed by the local server and are not sent to AI.', processedData: 'Uploaded file bytes', disable: 'Remove the document from Reader settings.' }),
  feature({ id: 'saved-library', name: 'Saved progress and restoration', category: 'Documents', purpose: 'Restore documents, settings, and exact reading positions.', location: 'Reader start screen', activation: 'Open a recent document.', defaultState: 'On', dependencies: 'IndexedDB', privacy: local, processedData: 'Document text, settings, and position', disable: 'Remove the document or clear site storage.' }),
  feature({ id: 'queue', name: 'Six-item reading queue', category: 'Documents', purpose: 'Keep recent reads available for low-friction re-entry.', location: 'Reader start screen', activation: 'Import documents.', defaultState: 'On', dependencies: 'IndexedDB', privacy: local, processedData: 'Recent document metadata', disable: 'Remove queued documents.' }),
  feature({ id: 'queue-resurfacing', name: 'Queue resurfacing', category: 'Documents', purpose: 'Offer a short two-minute return to an unfinished item.', location: settings, activation: 'Enable Queue resurfacing.', defaultState: 'Off', dependencies: 'Reading queue', privacy: local, processedData: 'Saved time and reading position', disable: 'Disable Queue resurfacing.' }),
  feature({ id: 'rsvp', name: 'RSVP playback', category: 'Reading', purpose: 'Present source-mapped words or phrases at a controlled pace.', location: 'Reader', activation: 'Press Play.', shortcut: 'Space', defaultState: 'Paused', dependencies: 'Recursive playback scheduler', privacy: local, processedData: 'Reading position and timing', disable: 'Pause playback.' }),
  feature({ id: 'navigation', name: 'Restart, previous, and next', category: 'Reading', purpose: 'Move through source-mapped RSVP chunks.', location: 'Reader dock', activation: 'Choose a navigation control.', shortcut: 'R / Left / Right', defaultState: 'Available', dependencies: 'None', privacy: local, processedData: 'Reading position', disable: 'Not applicable.' }),
  feature({ id: 'smart-rewind', name: 'Context-aware smart rewind', category: 'Reading', purpose: 'Return to the previous sentence or meaningful phrase instead of an arbitrary word count.', location: 'Reader dock', activation: 'Choose Rewind.', shortcut: 'Left arrow', defaultState: 'Available', dependencies: 'Sentence and phrase mapping', privacy: local, processedData: 'Current source position', disable: 'Not applicable.' }),
  feature({ id: 'reading-modes', name: 'Purpose-driven reading modes', category: 'Reading', purpose: 'Apply Skim, Deep Focus, or Study pacing and break presets.', location: settings, activation: 'Choose Reading mode.', defaultState: 'Deep Focus', dependencies: 'Mode presets', privacy: local, processedData: 'Selected reading intent', disable: 'Choose another mode.' }),
  feature({ id: 'calibration', name: 'Personal calibration', category: 'Reading', purpose: 'Set comfortable WPM, phrase size, and break tolerance.', location: 'First run and settings', activation: 'Complete calibration or choose Recalibrate.', defaultState: 'First run', dependencies: 'Reading profile', privacy: local, processedData: 'Comfort preferences', disable: 'Skip calibration or recalibrate.' }),
  feature({ id: 'reading-controls', name: 'Speed, chunk, and type controls', category: 'Reading', purpose: 'Adjust 50–1000 WPM, 1–5 words, 24–120px type, weight, and font.', location: settings, activation: 'Adjust the Reading controls.', defaultState: '280 WPM / 2 words / 72px / Times New Roman', dependencies: 'None', privacy: local, processedData: 'Display preferences', disable: 'Reset controls manually.' }),
  feature({ id: 'focus-point', name: 'Red focus character', category: 'Reading', purpose: 'Anchor the eye at the optimal recognition point with automatic CJK handling.', location: settings, activation: 'Enable Show focus point.', defaultState: 'On', dependencies: 'Tokenizer', privacy: local, processedData: 'Current chunk text', disable: 'Disable Show focus point.' }),
  feature({ id: 'semantic-grouping', name: 'Multilingual punctuation grouping', category: 'Reading', purpose: 'Attach punctuation to words across Latin, Chinese, Japanese, Arabic, Indic, Hebrew, Cyrillic, Greek, Korean, and Thai text.', location: settings, activation: 'Language detection and punctuation grouping are automatic; optional AI punctuation analysis enriches the next import.', defaultState: 'Local multilingual grouping on / AI off', dependencies: 'Intl.Segmenter with deterministic fallback; optional Gemma', privacy: 'AI receives only a short document sample when enabled.', processedData: 'Language/script sample and punctuation symbols only', disable: 'Disable AI punctuation analysis; deterministic local grouping remains active.' }),
  feature({ id: 'role-highlights', name: 'Subject, verb, and key-idea highlights', category: 'Reading', purpose: 'Color-code sentence roles independently of the focus character.', location: settings, activation: 'Enable Subject / verb / key highlights.', defaultState: 'Off', dependencies: 'Local grammatical heuristics', privacy: local, processedData: 'Sentence tokens', disable: 'Disable the highlight toggle.' }),
  feature({ id: 'context-ladder', name: 'Context ladder', category: 'Reading', purpose: 'Show Just Read, Now, and Next around the active phrase.', location: settings, activation: 'Enable Context ladder.', defaultState: 'Off', dependencies: 'Source mapping', privacy: local, processedData: 'Adjacent chunks', disable: 'Disable Context ladder.' }),
  feature({ id: 'focus-window', name: 'Focus window and eye anchor', category: 'Sensory', purpose: 'Reduce peripheral visual noise and optionally add a subtle horizontal line or viewport grid for eye anchoring.', location: settings, activation: 'Enable Focus window or Eye anchor; choose the eye anchor style independently.', defaultState: 'Off / line selected', dependencies: 'CSS overlays', privacy: local, processedData: 'Display preferences', disable: 'Disable Focus window and/or Eye anchor.' }),
  feature({ id: 'themes', name: 'Light, paper, dark, e-ink, and high-contrast themes', category: 'Sensory', purpose: 'Provide light, paper, dark, low-stimulation e-ink, true black/white high contrast, text, and background controls.', location: 'Reader settings', activation: 'Choose a theme, contrast, preset, or custom color.', defaultState: 'Paper / balanced', dependencies: 'None', privacy: local, processedData: 'Appearance preferences', disable: 'Return to the Paper theme.' }),
  feature({ id: 'motion', name: 'Motion smoothing and automatic focus hide', category: 'Sensory', purpose: 'Choose softened transitions; with a document open, navigation automatically hides after three seconds without pointer activity, leaving the centered RSVP phrase and progress bar.', location: 'Reader and settings', activation: 'Open a document. Pointer activity temporarily reveals controls; keyboard and voice commands do not.', defaultState: 'Automatic', dependencies: 'CSS transitions and pointer activity', privacy: local, processedData: 'Display timing and pointer activity', disable: 'Automatic focus hide is part of the Reader; pause or move the pointer to reveal controls.' }),
  feature({ id: 'background-media', name: 'Background image and video', category: 'Sensory', purpose: 'Use an uploaded image/video, direct media URL, or YouTube background.', location: 'Reader settings', activation: 'Open Settings, then upload media or apply a URL under Background media.', defaultState: 'Off', dependencies: 'Browser media playback and YouTube IFrame API commands', privacy: 'Uploaded files remain in the browser; URL hosts receive normal media requests.', processedData: 'Media file or URL', disable: 'Choose Remove.' }),
  feature({ id: 'background-controls', name: 'Background media controls', category: 'Sensory', purpose: 'Adjust opacity, scrim, blur, playback rate, pause, and looping.', location: settings, activation: 'Adjust Background media controls.', defaultState: '100% opacity / 35% dim / loop', dependencies: 'Background media', privacy: local, processedData: 'Media preferences', disable: 'Remove background media.' }),
  feature({ id: 'shortsform', name: 'Shortsform live narration mode', category: 'Reading', purpose: 'Read the imported book over full-bleed authorized gameplay with live sentence-window captions and per-word narration state.', location: 'Shortsform page', activation: 'Confirm rights, use an immediate YouTube preview or cache a compact local clip, then press Play.', defaultState: 'Paused / rights confirmations off', dependencies: 'Shared reading timeline, optional yt-dlp caching, and Edge TTS', privacy: 'Only the active reading chunk is sent to Edge TTS. YouTube preview uses the normal embed; optional compact footage is downloaded and cached by the local server.', processedData: 'Current reading chunk, selected voice, and authorized footage URL', disable: 'Pause playback or leave Shortsform mode.' }),
  feature({ id: 'character-voices', name: 'Automatic character voices', category: 'Reading', purpose: 'Detect recurring story characters and assign fitting installed narration voices.', location: 'Reader and Word Focus narration', activation: 'Turn on Narration after importing a story.', defaultState: 'Local deterministic cast; optional AI refinement', dependencies: 'Edge TTS voices; optional Gemma through local proxy', privacy: 'When AI is configured, the title, an opening excerpt, and available voice metadata are sent to OpenRouter.', processedData: 'Up to 14,000 opening characters, title, and voice names/locales/genders', disable: 'Turn off Narration.' }),
  feature({ id: 'ambient-audio', name: 'Bimodal ambient audio', category: 'Sensory', purpose: 'Provide brown noise, binaural beats, or a WPM-synced metronome with independent volume.', location: settings, activation: 'Choose an Ambient audio mode.', defaultState: 'Off', dependencies: 'Web Audio API', privacy: 'No recording occurs.', processedData: 'Playback pace and volume', disable: 'Choose Off.' }),
  feature({ id: 'adaptive', name: 'Adaptive pacing and focus ramp', category: 'Attention', purpose: 'Slow after difficulty and gradually accelerate when attention stabilizes.', location: settings, activation: 'Enable Adaptive pacing and/or Focus mode ramp.', defaultState: 'Off', dependencies: 'Session metrics', privacy: local, processedData: 'Rewinds, focus flags, timing, and comprehension', disable: 'Disable each toggle independently.' }),
  feature({ id: 'clarity', name: 'Clarity pauses', category: 'Attention', purpose: 'Add buffer time for long, rare, technical, or AI-identified difficult words.', location: settings, activation: 'Enable Buffer heavy words.', defaultState: 'Off', dependencies: 'Local complexity heuristic; optional Gemma', privacy: 'Optional AI complexity analysis receives a short sample.', processedData: 'Word forms and complexity labels', disable: 'Disable Buffer heavy words.' }),
  feature({ id: 'drift', name: 'Drift detection and recovery', category: 'Attention', purpose: 'Detect rewinds, speed changes, tab switching, inactivity, and optional gaze loss, then restore context.', location: settings, activation: 'Enable Drift recovery.', defaultState: 'Off', dependencies: 'Browser visibility and session metrics', privacy: local, processedData: 'Interaction timing and focus signals', disable: 'Disable Drift recovery.' }),
  feature({ id: 'focus-state', name: 'Losing focus / Locked in', category: 'Attention', purpose: 'Switch pacing immediately as attention fluctuates.', location: 'Reader dock', activation: 'Choose Losing focus or Locked in.', defaultState: 'Available', dependencies: 'Adaptive scheduler', privacy: local, processedData: 'Manual focus signal', disable: 'Not applicable.' }),
  feature({ id: 'breaks', name: 'Manual and fatigue-aware micro-breaks', category: 'Attention', purpose: 'Pause for 5–20 seconds with context, breathing space, and a stable return point.', location: 'Reader dock and settings', activation: 'Choose Break or enable Auto micro-breaks.', shortcut: 'B', defaultState: 'Manual available / automatic off', dependencies: 'Session metrics', privacy: local, processedData: 'Reading timing and recent context', disable: 'Disable Auto micro-breaks; close manual breaks.' }),
  feature({ id: 'transitions', name: 'Landing, primer, sprint, and cooldown rituals', category: 'Attention', purpose: 'Reduce start/stop friction with a countdown, restart primer, timed sprint completion, and session cooldown.', location: 'Reader overlays and settings', activation: 'Start, restart, or complete a sprint/session.', defaultState: 'Restart primer on', dependencies: 'Playback state', privacy: local, processedData: 'Session timing and nearby context', disable: 'Disable Restart primer and set Sprint length to 0.' }),
  feature({ id: 'working-memory', name: 'Who / What / Where hold', category: 'Comprehension', purpose: 'Pause and summarize the current section to offload working memory.', location: 'Reader overlay', activation: 'Open a break/context hold.', defaultState: 'Local fallback available / AI off', dependencies: 'Source mapping; optional Gemma', privacy: 'AI receives only nearby text when enabled.', processedData: 'Nearby passage', disable: 'Disable AI summaries and close the overlay.' }),
  feature({ id: 'sense-checks', name: 'Quick sense checks', category: 'Comprehension', purpose: 'Ask whether the passage made sense and adapt pacing from the answer.', location: settings, activation: 'Enable Quick sense checks.', defaultState: 'Off', dependencies: 'Session metrics', privacy: local, processedData: 'One-tap comprehension response', disable: 'Disable Quick sense checks.' }),
  feature({ id: 'quizzes', name: 'AI micro-quizzes', category: 'Comprehension', purpose: 'Generate optional grounded retention checks from the current passage.', location: settings, activation: 'Enable AI micro-quizzes.', defaultState: 'Off', dependencies: 'Gemma through local proxy', privacy: 'Only nearby text is sent to OpenRouter.', processedData: 'Nearby passage and reading mode', disable: 'Disable AI micro-quizzes.' }),
  feature({ id: 'reactions', name: 'Active Echo notes and reactions', category: 'Comprehension', purpose: 'Mark important, confusing, or understood points and review them after the session.', location: 'Reader dock and Notes', activation: 'Choose Mark, Confused, or Clear.', shortcut: 'I / 2 / 1', defaultState: 'Available', dependencies: 'IndexedDB session storage', privacy: local, processedData: 'Reaction type, excerpt, and position', disable: 'Delete the document or clear site storage.' }),
  feature({ id: 'feedback', name: 'Calm focus feedback', category: 'Comprehension', purpose: 'Show two-minute focus nudges, actual reading pace, and locally persisted consistency streaks without noisy rewards.', location: 'Reader status and settings', activation: 'Enable Calm streaks and nudges.', defaultState: 'Off', dependencies: 'Session metrics and localStorage', privacy: local, processedData: 'Focused time, date, and reading consistency', disable: 'Disable Calm streaks and nudges or clear site storage.' }),
  feature({ id: 'tone', name: 'Attention and tone indicators', category: 'Comprehension', purpose: 'Signal technical, warning, emotional, or calm passages without interrupting reading.', location: settings, activation: 'Enable Tone indicators.', defaultState: 'On', dependencies: 'Local text heuristics', privacy: local, processedData: 'Current sentence', disable: 'Disable Tone indicators.' }),
  feature({ id: 'progress', name: 'Linear progress and section milestones', category: 'Progress', purpose: 'Maintain spatial orientation with word progress, time remaining, and paragraph/section dots.', location: 'Reader progress bar', activation: 'Import a document; toggle Section milestones.', defaultState: 'On', dependencies: 'Source mapping', privacy: local, processedData: 'Position and section boundaries', disable: 'Disable Section milestones.' }),
  feature({ id: 'sprints', name: 'Reading sprints', category: 'Progress', purpose: 'Run calm 5, 10, 15, or 25 minute focus sessions.', location: 'Reader dock and settings', activation: 'Choose a Sprint length, then Sprint.', defaultState: 'Off', dependencies: 'Session timer', privacy: local, processedData: 'Focused time', disable: 'Set Sprint length to 0.' }),
  feature({ id: 'text-viewer', name: 'Source-mapped text viewer', category: 'Search', purpose: 'Browse the complete document and click any word to jump.', location: 'Text modal', activation: 'Choose Text.', shortcut: 'V', defaultState: 'On demand', dependencies: 'Source mapping', privacy: local, processedData: 'Document text and position', disable: 'Close the modal.' }),
  feature({ id: 'exact-search', name: 'Exact text search', category: 'Search', purpose: 'Find literal words and phrases with highlights and previous/next controls.', location: 'Text modal', activation: 'Open Text and type a query.', shortcut: 'V', defaultState: 'On demand', dependencies: 'None', privacy: local, processedData: 'Search query', disable: 'Clear the search field.' }),
  feature({ id: 'semantic-search', name: 'Local semantic document search', category: 'Search', purpose: 'Find paraphrased ideas with section-aware passages and source-grounded results.', location: 'Semantic search modal', activation: 'Choose Search or press Ctrl/Cmd+K.', shortcut: 'Ctrl/Cmd+K', defaultState: 'On demand', dependencies: 'MiniLM ONNX with WebGPU/WASM fallback', privacy: 'Passages, embeddings, and query vectors remain local.', processedData: 'Document passages and query', disable: 'Cancel indexing or delete the document index.' }),
  feature({ id: 'semantic-ai', name: 'AI semantic reranking and answers', category: 'Search', purpose: 'Rerank retrieved passages and produce a concise, cited answer without sending the full book.', location: settings, activation: 'Enable AI semantic-search answer.', defaultState: 'Off', dependencies: 'Gemma through local proxy', privacy: 'Only the top retrieved passages and query are sent to OpenRouter.', processedData: 'Query and up to eight passages', disable: 'Disable AI semantic-search answer.' }),
  feature({ id: 'voice', name: 'Voice commands', category: 'Sensors', purpose: 'Control play, pause, break, rewind, next, settings, and Guide by voice.', location: settings, activation: 'Enable Voice commands and grant microphone access.', defaultState: 'Off', dependencies: 'Browser SpeechRecognition', privacy: 'Browser speech recognition processes spoken commands; Celere stores no audio.', processedData: 'Recognized command transcript', disable: 'Disable Voice commands or revoke microphone permission.' }),
  feature({ id: 'eye', name: 'Local eye-away detection', category: 'Sensors', purpose: 'Pause and restore context after prolonged gaze loss.', location: settings, activation: 'Enable Experimental eye-away detection and grant camera access.', defaultState: 'Off', dependencies: 'MediaPipe Face Landmarker', privacy: 'Camera frames and iris landmarks are processed locally and never stored or transmitted.', processedData: 'Live camera frames and transient landmarks', disable: 'Disable eye-away detection or revoke camera permission.' }),
  feature({ id: 'runtime', name: 'Runtime and privacy status', category: 'Privacy', purpose: 'Show microphone, camera, vector-storage, and AI data-flow status.', location: 'Reader settings and Guide', activation: 'Open settings or Guide.', defaultState: 'Available', dependencies: 'Feature registry', privacy: 'No additional processing.', processedData: 'Current feature state', disable: 'Not applicable.' }),
  feature({ id: 'deletion', name: 'Document and index deletion', category: 'Privacy', purpose: 'Delete text, progress, notes, queue state, and local semantic vectors.', location: settings, activation: 'Choose Remove document.', defaultState: 'Available', dependencies: 'IndexedDB', privacy: local, processedData: 'Selected document records', disable: 'Not applicable.' }),
  feature({ id: 'guide', name: 'Searchable feature Guide', category: 'Help', purpose: 'Explain every feature, shortcut, dependency, privacy implication, processed data, disable path, and runtime status.', location: 'Guide page', activation: 'Choose Guide.', defaultState: 'Available', dependencies: 'Feature registry', privacy: local, processedData: 'Guide search query', disable: 'Return to Reader.' }),
  feature({ id: 'shortcuts', name: 'Keyboard shortcut reference', category: 'Help', purpose: 'Expose playback, navigation, search, reactions, settings, and break shortcuts.', location: 'Reader dock and Guide', activation: 'Choose Shortcuts.', defaultState: 'Available', dependencies: 'Keyboard events', privacy: local, processedData: 'Key presses outside form fields', disable: 'Close the shortcut overlay.' }),
]
